// Generated by CoffeeScript 1.7.1
(function() {
  var addListener, i, _i, _len, _ref;

  addListener = function(element, type, callback) {
    if (element.addEventListener) {
      element.addEventListener(type, callback);
    } else {
      if (element.attachEvent) {
        element.attachEvent("on" + type, callback);
      }
    }
  };

  _ref = document.getElementsByTagName("a");
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    i = _ref[_i];
    addListener(i, "click", function() {
      ga("send", "event", "link", "click", i.href);
    });
  }

}).call(this);

//# sourceMappingURL=hnletk.map
